BikeShare/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from account.views import registration_view, logout_view, login_view


app_name = 'bikeshare'

urlpatterns = [

    path('', views.home, name='bikeshare-main'),
    path('howitworks/', views.how_it_works, name='howitworks'),
    path('login/', login_view, name='login'),
    path('signup/', registration_view, name='signup'),
    path('logout/', logout_view, name='logout'),
    path('top-up/', views.top_up_balance, name='top-up'),
    path('top-up/submit/', views.submit_top_up, name='top-up-submit'),
    path('pay-balance/', views.pay_balance, name='pay-balance'),
    path('pay-balance/submit/', views.submit_pay_balance, name='pay-balance-submit'),

    path('customer/', views.customer_page, name='bikeshare-customer'),
    path('customer/<int:station_id>/rent', views.rent_bike, name='rent_bike'),
    path('customer/<int:order_id>/return', views.return_bike, name='return_bike'),
    path('customer/<int:order_id>/report_faulty', views.report_faulty, name='report_faulty'),

    path('manager/', views.manager_page, name='bikeshare-manager'),
    path('operator/', views.operator_page, name='bikeshare-operator'),
    path('operator/<int:bike_id>/repair_bike', views.repair_bike, name='repair_bike'),
    path('operator/<int:bike_id>/move_bike', views.move_bike, name='move_bike'),
    path('operator/<int:bike_id>/delete_bike/', views.delete_bike, name='delete_bike'),
    path('create_station/', views.create_station, name='create_station'),

]

BikeShareSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from BikeShare import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('BikeShare.urls'))
]

BikeShare/models.py
from django.db import models
from django import forms
from django.utils import timezone
from django.contrib.auth.models import User, AbstractBaseUser, BaseUserManager
from BikeShareSystem import settings
# Create your models here.


class Station(models.Model):
    station_name = models.CharField(max_length=100, default="")
    station_latitude = models.FloatField(null=True)
    station_longitude = models.FloatField(null=True)

    def __str__(self):
        return self.station_name

    @property
    def number_of_bikes(self):
        available_bikes = self.bike_set.all().filter(in_use=False, is_faulty=False)
        return available_bikes.count()


class Bike(models.Model):

    in_use = models.BooleanField(default=False)
    is_faulty = models.BooleanField(default=False)
    station = models.ForeignKey(Station, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Bikes'

    def current_usage(self):
        if self.in_use:
            return "In Use"
        else:
            return "Free"

    def condition(self):
        if self.is_faulty:
            return "Faulty"
        else:
            return "Good"



class Order(models.Model):

    bike = models.ForeignKey(Bike, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=0)
    start_station = models.ForeignKey(Station, on_delete=models.CASCADE, default="", related_name='startstation')
    end_station = models.ForeignKey(Station, on_delete=models.CASCADE, default=None, null=True, blank=True)
    start_time = models.DateTimeField(default=timezone.now)
    check_out_time = models.DateTimeField(default=timezone.now)
    due_amount = models.FloatField(default=0.00)
    fix_amount = models.FloatField(default=0.00)
    is_complete = models.BooleanField(default=False)

    def __str__(self):
        return "Order ID: {}\nCustomer ID: {}\nBike ID: {} ".format(self.pk, self.user, self.bike)

BikeShare/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from account.models import Account
from .models import Bike, Station
from django.contrib.auth import authenticate


class StationForm(forms.ModelForm):
    class Meta:
        model = Station
        fields = ['station_name', 'station_latitude', 'station_longitude']  # Add necessary fields from your Station model

class TopUpForm(forms.Form):
    money = forms.FloatField(label='Top Up Amount', max_value=100.0, min_value=5.0)


class PayBalanceForm(forms.Form):
    money = forms.FloatField(label='Payment Amount')


class LocationForm(forms.ModelForm):
    locations = forms.ModelChoiceField(queryset=Station.objects.all(), label='Station Location')

    class Meta:
        model = Station
        fields = ['locations']


class RegistrationForm(UserCreationForm):

    ROLE_CHOICES = (
        ('Customer', 'Customer'),
        ('Operator', 'Operator'),
        ('Manager', 'Manager'),
    )
    email = forms.EmailField(max_length=60, help_text='Add valid email address')

    class Meta:
        model = Account
        fields = ["username", "email", "password1", "password2"]


class AccountAuthenticationForm(forms.ModelForm):

    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model = Account
        fields = ('username', 'password')

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        if not authenticate(username=username, password=password):
            raise forms.ValidationError('Invalid Login')

BikeShare/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Bike, Station, Order
from account.models import Account
import datetime
from .forms import TopUpForm, PayBalanceForm, LocationForm
from django.db.models import Sum
from django.db.models import Count
import matplotlib.pyplot as plt
from io import BytesIO
import base64
from django.core import serializers
from django.http import HttpResponse
from .forms import StationForm

def create_station(request):
    if request.method == 'POST':
        form = StationForm(request.POST)
        if form.is_valid():
            form.save()  # Save the form data to create a new Station object
            return redirect('bikeshare:bikeshare-main')  # Redirect to a page after creation
    else:
        form = StationForm()

    return render(request, 'create_station.html', {'form': form})

def home(request):
    return render(request, 'home.html')


def city_map(request):

    # passes station objects to city map html
    all_stations_map = serializers.serialize("json", Station.objects.all())
    return render(request, 'city_map.html', context={'all_stations_map':all_stations_map})


def how_it_works(request):
    locations = Station.objects.all()
    return render(request, 'how_it_works.html', context={'locations':locations})


def customer_page(request):

    all_stations = Station.objects.all()
    all_bikes = Bike.objects.all()
    customers_orders = Order.objects.all().filter()
    all_stations_map = serializers.serialize("json", Station.objects.all())

    form = LocationForm()
    context = {
        'all_stations': all_stations,
        'all_bikes': all_bikes,
        'customers_orders': customers_orders,
        'form': form,
        'all_stations_map': all_stations_map}

    return render(request, 'customer_page.html', context=context)


def rent_bike(request, station_id):

    # get station object from the id passed to the function
    station = get_object_or_404(Station, pk=station_id)
    # take the first bike from the station which is not in use or faulty
    bike = station.bike_set.all().filter(in_use=False, is_faulty=False).first()
    rented_bike = get_object_or_404(Bike, pk=bike.id)
    # get user object
    user = get_object_or_404(Account, pk=request.POST.get('user_id', False))

    # take the time the rental began
    time = datetime.datetime.now()

    # increment the users 'hires in progress' attribute
    user.hires_in_progress += 1
    user.save()

    # create a new order with bike, user, station and start time
    new_order = Order(bike=rented_bike, user=user, start_station=station, start_time=time)
    new_order.save()

    # change bike in use to true to stop it from being rented again
    bike.in_use = True
    bike.save()

    all_stations = Station.objects.all()
    all_bikes = Bike.objects.all()
    customers_orders = Order.objects.all()
    context = {
        'user':user,
        'all_stations': all_stations,
        'all_bikes': all_bikes,
        'customers_orders':customers_orders,
    }
    return render(request, 'customer_page.html', context=context)


def return_bike(request, order_id):

    # calculate cost from the start and end time, at 5 per hour rounded up, or €30 a day
    def calculate_cost(starttime, endtime):
        if starttime.date() == endtime.date():
            hours_used = endtime.hour - starttime.hour
            cost = (hours_used + 1) * 5.00
        else:
            cost = 30.0 * (endtime.day - starttime.day)
        return cost

    order = get_object_or_404(Order, pk=order_id)

    if request.method == 'POST':
        form = LocationForm(request.POST)
        if form.is_valid():

            # get return station location

            start_time = order.start_time
            end = datetime.datetime.now()
            location = form.cleaned_data['locations']
            station = get_object_or_404(Station, pk=location.pk)

            # complete order object with end station, check out time, cost, and is complete
            order.end_station = station
            order.check_out_time = end
            order_cost = calculate_cost(start_time, end)
            order.is_complete = True
            order.due_amount = order_cost


            # add cost to user object and decrement hires in progress
            userid = order.user
            user = get_object_or_404(Account, pk=userid.pk)
            user.amount_owed += order_cost
            user.hires_in_progress -= 1
            user.save()

            bike = get_object_or_404(Bike, pk=order.bike.pk)
            bike.in_use = False
            bike.save()

            order.save()

            return redirect('bikeshare:bikeshare-customer')

        else:
            form = LocationForm()

        all_stations = Station.objects.all()
        all_bikes = Bike.objects.all()
        customers_orders = Order.objects.all()

        context = {
            'form': form,
            'order':order,
            'all_stations': all_stations,
            'all_bikes': all_bikes,
            'customers_orders':customers_orders,
        }
    return render(request, 'return_bike.html', context=context)


def top_up_balance(request):
    form = TopUpForm()
    return render(request, 'top_up.html', {'form': form})


def submit_top_up(request):

    # user tops up wallet balance

    success_message = ""

    if request.method == 'POST':
        form = TopUpForm(request.POST)
        if form.is_valid():
            user = request.user
            money = int(form.cleaned_data['money'])
            user.wallet_balance += money
            success_message = "You have topped up by €{}".format(money)
            user.save()
    else:
        form = TopUpForm()

    if success_message:
        context = {'success_message':success_message, 'form':form}
    else:
        context = {'form':form}
    return render(request, 'top_up.html', context=context)


def pay_balance(request):

    form = PayBalanceForm()

    return render(request, 'pay_balance.html', context={'form':form})


def submit_pay_balance(request):

    msg = ""

    if request.method=='POST':
        form = PayBalanceForm(request.POST)
        if form.is_valid():
            user = request.user
            payment_amount = int(form.cleaned_data['money'])
            if payment_amount <= user.wallet_balance and payment_amount <= user.amount_owed:
                user.wallet_balance -= payment_amount
                user.amount_owed -= payment_amount
                user.save()
                if user.amount_owed == 0:
                    msg = "You have paid off all your balance!"
                else:
                    msg = "You have paid €{}. You still owe €{}".format(payment_amount, user.amount_owed)
            elif payment_amount > user.wallet_balance:
                msg = "You don't have enough money in your wallet"
            elif payment_amount > user.amount_owed:
                msg = "You don't owe this much"

            if msg:
                context = {'msg':msg, 'form':form}
            else:
                context = {'form':form}
        else:
            form = TopUpForm()
            context={'form':form}

        return render(request, 'pay_balance.html', context=context)


def report_faulty(request, order_id):

    # add fix amount to order
    order = get_object_or_404(Order, pk=order_id)
    order.fix_amount += 20.0
    order.save()

    # charge customer #15
    customer = get_object_or_404(Account, pk=order.user.id)
    customer.amount_owed += 15.00
    customer.save()

    bike = order.bike
    bike.is_faulty = True
    bike.save()

    # warn user they have been charged
    message = "You have been charged €15 to repair bike damages. "

    all_stations = Station.objects.all()
    all_bikes = Bike.objects.all()
    customers_orders = Order.objects.all()

    context = {
        'all_stations': all_stations,
        'all_bikes': all_bikes,
        'customers_orders': customers_orders,
        'repair_message': message,
    }
    return render(request, 'customer_page.html', context=context)


def operator_page(request):

    faultybikes = Bike.objects.all().filter(is_faulty=True)
    all_bikes = Bike.objects.all().filter()

    move_stations = Station.objects.all()

    context = {
        'faulty_bikes': faultybikes,
        'all_bikes': all_bikes,
        'move_stations': move_stations}

    return render(request, 'operator_page.html', context=context)


def repair_bike(request, bike_id):

    bike = get_object_or_404(Bike, pk=bike_id)
    bike.is_faulty = False
    bike.save()

    faultybikes = Bike.objects.all().filter(is_faulty=True)
    all_bikes = Bike.objects.all().filter()
    move_stations = Station.objects.all()

    context = {
        'faulty_bikes': faultybikes,
        'all_bikes': all_bikes,
        'move_stations': move_stations}
    return render(request, 'operator_page.html', context=context)


def move_bike(request, bike_id):

    bike = get_object_or_404(Bike, pk=bike_id)
    msg =""
    if request.method == 'POST':
        form = LocationForm(request.POST)
        if form.is_valid():
            location = form.cleaned_data["locations"]
            if location != bike.station:
                msg = "You have moved bike from {} to {} Bike Station.".format(bike.station, location)
            else:
                msg = "Bike is already at {} Bike Station".format(bike.station)
            station = get_object_or_404(Station, pk=location.pk)
            bike.station = station
            bike.save()
        else:
            form = LocationForm()

        if msg:
            context = {'msg':msg,
                'bike': bike,
                       'form': form}
        else:
            context={'bike': bike, 'form': form}

    return render(request, 'move_bike.html', context=context)

def delete_bike(request, bike_id):
    bike = get_object_or_404(Bike, pk=bike_id)
    bike.delete()
    return redirect('bikeshare:bikeshare-operator')

BikeShare/templates/activity_page.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}


    {% if request.user %}


    {% endif %}


{% endblock %}



</body>
</html>

BikeShare/templates/customer_page.html
<head>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCcO7TBAhqCQGkzRxioL1Ntt7i66SeOBig&callback=initMap"
  type="text/javascript"></script>
</head>

{% extends 'base.html' %}

    <!DOCTYPE html>
    <head>
      <script async defer
                src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCcO7TBAhqCQGkzRxioL1Ntt7i66SeOBig&callback=initMap"
                type="text/javascript"></script>
    </head>

{% block content %}
    <body>
    <br>
    <h5>Your Details</h5>
    <table align="center">
        <thead>
        <tr>
            <th>Username</th>
            <th>Email Address</th>
            <th>Hires in Progress</th>
            <th>Wallet balance</th>
            <th>Amount Owed</th>

        </tr>
        </thead>
        <tbody>
        <tr>
            <td>{{ request.user.username }}</td>
            <td>{{ request.user.email }}</td>
            <td>{{ request.user.hires_in_progress }}</td>
            <td>€{{ request.user.wallet_balance }}</td>
            <td>€{{ request.user.amount_owed }}</td>
        </tr>
        </tbody>
    </table>

    <div class="container" align="center" style="padding: 10px">

        <button type="button" id="cancel" class="cancelbtn waves-effect waves-light btn"
                onclick="location.href='{% url 'bikeshare:top-up' %}'">Top Up Balance
        </button>
        <button type="button" id="cancel" class="cancelbtn waves-effect waves-light btn"
                onclick="location.href='{% url 'bikeshare:pay-balance' %}'">Pay Balance
        </button>
    </div>
    <br>
    {% if repair_message %}

        <a><center>{{ repair_message }} </center></a>

    {% endif %}


    {%  if request.user.hires_in_progress > 0  %}

    <h5>Your Current Hires</h5>
    <table>
        <thead>
        <tr>
            <th>Bike ID</th>
            <th>Start Station</th>
            <th>Start Time</th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for order in customers_orders %}

            {% if not order.is_complete and order.user.pk == request.user.id %}

                <form action="{% url 'bikeshare:return_bike' order.id%}" method="post">
                    {% csrf_token %}
                    <tr>
                        {% if not order.bike.is_faulty %}
                        <th><label>{{ order.bike.id }}</label></th>
                         {% else %}
                            <th><label>{{ order.bike.id }} (Faulty)</label></th>
                         {% endif %}

                        <th><label> {{ order.start_station }}</label></th>
                        <th><label>{{ order.start_time }}</label></th>
                        <th>
                            <button type="submit" class="cancelbtn waves-effect waves-light btn" name="return_station"
                                    value="">Return Bike
                            </button>
                </form>
                <th><br>
                    {% if not order.bike.is_faulty %}
                    <form action="{% url 'bikeshare:report_faulty' order.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="cancelbtn waves-effect waves-light btn" name="report_faulty"
                                value="">Report Faulty
                        </button>
                    {% endif %}
                    </form>
                </th>
                </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table>

    {% endif %}

    <br>

    <h5>Station Locations</h5>




    <br>

    {% if request.user.amount_owed >= 30.00 %}

        <h5>Rent a Bike<a> - Please repay your balance before renting another bike.</a></h5>

    {% elif request.user.hires_in_progress > 3 %}

        <h5>Rent a Bike<a> - Please return one or more bikes before renting another.</a></h5>

    {% else %}

        <h5>Rent a Bike</h5>
    {% endif %}

    <table>
        <thead>
        <tr>
            <th align="center">Station Name</th>
            <th>Available Bikes</th>
            <th>Rent Bike</th>
        </tr>
        </thead>
        <tbody>
        {% for station in all_stations %}
            <form action="{% url 'bikeshare:rent_bike' station.id %}" method="post">
                {% csrf_token %}
                <tr>
                    <td>
                        <label>{{ station.station_name }} </label>
                    </td>
                    <td>
                        <label>{{ station.number_of_bikes }}</label>
                    </td>
                    <td>

                     {% if request.user.amount_owed >= 30.00 or request.user.hires_in_progress > 3 %}

                        {% if station.number_of_bikes > 0 %}
                            <button type="submit" class="cancelbtn waves-effect waves-light btn" name="user_id"
                                    value="{{ request.user.id }}" disabled>Rent Bike
                            </button>
                        {% else %}
                            <a>No bikes available</a>
                        {% endif %}

                    {% else %}

                    {% if station.number_of_bikes > 0 %}
                            <button type="submit" class="cancelbtn waves-effect waves-light btn" name="user_id"
                                    value="{{ request.user.id }}">Rent Bike
                            </button>
                        {% else %}
                            <a>No bikes available</a>
                        {% endif %}


                    {% endif %}


                    </td>
                </tr>
            </form>
        {% endfor %}

        </tbody>
    </table>
    <br><br>

{% endblock %}

</body>

</html>

BikeShare/templates/manager_page.html
{% extends 'base.html' %}

{% block content %}
<style>
        /* Style for the button */
        .create-station-button {
            display: inline-block;
            padding: 10px 20px;
            background-color: #3498db; /* Blue color */
            color: white;
            text-decoration: none;
            border-radius: 5px;
            border: none;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        /* Style for button hover effect */
        .create-station-button:hover {
            background-color: #2980b9; /* Darker shade of blue on hover */
        }
    </style>

<body>
    <a class="create-station-button" href="{% url 'bikeshare:create_station' %}">Create New Station</a>
    <div class="container" align = "center">
        {% if total_Profit > 0.0 %}
            <h3>Station Profit Contibution</h3>
            <img src="data:image/png;base64, {{ station_profit }}" alt = "Profit per Station - Pie Chart : Unavailable">
        {% else %}
            <h4>Business in Loss : € {{ total_Profit}}</h4>
        {% endif %}
    </div>
    <div class="container" align = "center">
        <h3>Route Frequency Distribution</h3>
        <img src="data:image/png;base64, {{ route_frequency }}" alt = "Route Frequencies - Horizontal bar graph : Unavailable">
    </div>
    <div class="container" align = "center">
        <h3>Station Bike Count</h3>
        <img src="data:image/png;base64, {{ station_bike_count }}" alt = "Station Bike Count - Bar Graph : Unavailable">
    </div>
    <div class = "container" align = "center">
        <h3>Star Users</h3>
        {% if star_users %}
            <table>
                <tr align="center">
                    <th align = "center"><font color="#4B0082">USER</font></th>
                    <th align = "center"><font color="#4B0082">Number of Rides</font></th>
                </tr>
                {% for user in star_users %}
                    <tr>
                        <td>{{ user.user__username }}</td>
                        <td>{{ user.usages }}</td>
                    </tr>
                {% endfor %}
            </table>
        {% else %}
            <h5>Star Users : Unavailable</h5>
        {% endif %}
    </div>
</body>
{% endblock %}

BikeShare/templates/move_bike.html
{% extends 'base.html' %}

{% block content %}


    <h4>
        <center>Move Bike</center>
    </h4>
    <h6>
        <center>Bike ID: {{ bike.id }}</center>
    </h6>
    <h6>
        <center>Condition: {{ bike.condition }}</center>
    </h6>
    <h6>
        <center>Current Location: {{ bike.station }}</center>
    </h6>

    {% if msg %}

        <a><center><br>{{ msg }}<br><br></center></a>

    {% endif %}

    <div class="container" align="center">

        <form method="post" name="movebikeform" action="{% url 'bikeshare:move_bike' bike.id %}"
              enctype="multipart/form-data">
            {% csrf_token %}
            <label for="id_locations">Station location:</label>
            <select class="browser-default" id="id_locations" name="locations" required>
                {% for field in form.visible_fields %}
                    <option value="{{ field }}"></option>
                {% endfor %}
            </select>
        <br>
            <button type="submit" class="waves-effect waves-light btn">Move Bike</button>        </form>
            <button id="cancel" class="cancelbtn waves-effect waves-light btn"
            onclick="location.href='{% url 'bikeshare:bikeshare-operator' %}'">Return
            </button>
        <br>


    </div>

{% endblock %}

BikeShare/templates/navbar.html
{% block content %}
<body>

 <nav class="nav-extended">
    <div class="nav-wrapper">
      <a href="#" class="brand-logo"> &nbsp; BikeShare</a>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li>
              {% if request.user.is_authenticated  %}
                  <li class="tab">Hello, {{ request.user.username }}  </li><li> <a href="{% url 'bikeshare:logout' %}">Logout</a></a></li>
            {% else %}
                  <li>   <a href="{% url 'bikeshare:login' %}">Login </li></a><li> <a href="{% url 'bikeshare:signup' %}"> Register</a></li>
        {% endif %}
          </li>

      </ul>
    </div>
    <div class="nav-content">
      <ul class="tabs tabs-transparent">
        <li class="tab"><a href="{% url 'bikeshare:bikeshare-main' %}">Home</a></li>
          <li class="tab"><a href="{% url 'bikeshare:howitworks' %}">How it Works</a></li>
          {% if request.user.is_superuser %}
        <li class="tab"><a class="active" href="{% url 'bikeshare:bikeshare-customer' %}">Rent A Bike</a></li>
          <li class="tab"><a class="active" href="{% url 'bikeshare:bikeshare-operator' %}">Operator's Page</a></li>
         <li class="tab"><a class="active" href="{% url 'bikeshare:bikeshare-manager' %}">Manager's Page</a></li>
        {% elif request.user.role == 'Customer' %}
        <li class="tab"><a class="active" href="{% url 'bikeshare:bikeshare-customer' %}">Rent A Bike</a></li>
          {% elif request.user.role == 'Operator' %}
          <li class="tab"><a class="active" href="{% url 'bikeshare:bikeshare-operator' %}">Operator's Page</a></li>
         {% elif request.user.role == 'Manager' %}
         <li class="tab"><a class="active" href="{% url 'bikeshare:bikeshare-manager' %}">Manager's Page</a></li>
        {% endif %}

      </ul>
    </div>
  </nav>



{% endblock %}

BikeShare/templates/operator_page.html
{% extends 'base.html' %}

{% block content %}



<br>
<h5>Bike Activity</h5>
<br>
    <table>
        <thead>
        <tr>
            <th><label>Bike ID</label></th>
            <th><label>Current Location</label></th>
            <th><label>Condition</label></th>
            <th><label>Move Bike</label></th>
            <th><label>Repair</label></th>
        </tr>
        </thead>
    <tbody>
    {% for bike in all_bikes %}
    <tr>
    <th><label>{{ bike.id }}</label></th>
        <th><label>{{ bike.station }}</label></th>
    <th><label> {{ bike.condition }}</label></th>
    <th><label>    {% if bike.in_use %} <br>Bike currently in use<br><br> {% else %}
   <form action="{% url 'bikeshare:move_bike' bike.id %}" method="post">{% csrf_token %}
       <button type="submit" class="cancelbtn waves-effect waves-light btn" name="return_station">Move Bike</button><br>
   </form>
    {% endif %}
    </label></th>
        <th>
            {% if bike.is_faulty %}<label> <form action="{% url 'bikeshare:repair_bike' bike.id %}" method="post">{% csrf_token %}
            <button type="submit" class="cancelbtn waves-effect waves-light btn" name="repair_bike" value="">Repair Bike </button>
    </form></label>{% endif %}</th>
        <th>
            <label> <form action="{% url 'bikeshare:delete_bike' bike.id %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="Delete Bike">
    </form></label></th>
    </tr>
    {% endfor %}
    </tbody>
    </table>

{% endblock %}

BikeShare/templates/pay_balance.html
{% extends 'base.html' %}

{% block content %}


<form method="post" action="{% url 'bikeshare:pay-balance-submit' %}">
{% csrf_token %}

  <h3><center>PAY BALANCE</center> </h3>
    <h6><center>YOUR BALANCE: €{{ request.user.wallet_balance }}</center> </h6>
    <h6><center>AMOUNT OWED: €{{ request.user.amount_owed }}</center> </h6>

    {% if msg %}

        <a><center>{{ msg }}</center></a>

    {% endif %}
    <div class="container">
        {{ form }}
  </div>

  <div class="container" align="center" >
    <br>
    <button type="submit" id ="topup" class="waves-effect waves-light btn">confirm
    </button>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    <button type="button" id="cancel" class="cancelbtn waves-effect waves-light btn" onclick="location.href='{% url 'bikeshare:bikeshare-customer' %}'">
      Return</button>

  </div>
</form>

{% endblock %}

BikeShare/templates/return_bike.html
{% extends 'base.html' %}

{% block content %}


    <h3>
        <center>Return Bike</center>
    </h3>
    <h6>
        <center>Start Location: {{ order.start_station }}</center>
    </h6>


     <div class="container" align="center">

        <form method="post" name="movebikeform" action="{% url 'bikeshare:return_bike' order.id %}"
              enctype="multipart/form-data">
            {% csrf_token %}
            <label for="id_locations">Station location:</label>
            <select class="browser-default" id="id_locations" name="locations" required>
                {% for field in form.visible_fields %}
                    <option value="{{ field }}"></option>
                {% endfor %}
            </select>
        <br>
            <button type="submit" class="waves-effect waves-light btn">Return Bike</button>        </form>
            <button id="cancel" class="cancelbtn waves-effect waves-light btn"
            onclick="location.href='{% url 'bikeshare:bikeshare-customer' %}'">Go Back
            </button>
        <br>


    </div>






{% endblock %}

BikeShare/templates/top_up.html
{% extends 'base.html' %}


{% block content %}

<form method="post" action="{% url 'bikeshare:top-up-submit' %}">
{% csrf_token %}

  <h3><center>TOP UP</center> </h3>
    <h6><center>YOUR BALANCE: {{ request.user.wallet_balance }}</center> </h6>
    {% if success_message %}

    <a><center>{{ success_message }}</center></a>

    {% endif %}
    <br>
    <div class="container">
        {{ form }}
  </div>
  
  <div class="container">
    <label for="card"><b>Card number</b></label>
    <input type="number" placeholder="enter your card number" required>
    <br>
    <label for="code"><b>3digital-code</b></label>
    <input type="number" placeholder="enter your 3digital-code" required>
    
  <div class="container" align="center" >
    <br>
    <button type="submit" id ="topup" class="waves-effect waves-light btn">confirm</button>
    &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    <button type="button" id="cancel" class="cancelbtn waves-effect waves-light btn" onclick="location.href='{% url 'bikeshare:bikeshare-customer' %}'">Return</button>

  </div>
</form>
{% endblock  %}